### ISSUE TITLE
prevent double-tap zoom on iOS

### ISSUE THREAD

**Issue by johnteske** [vectorscores/scores#18]
This may not be required once the timing controls are in place--I don't imagine many scores would benefit from a "tap/click to advance" format.

A possible solution, if needed:

https://gist.github.com/johan/2047491

**Comment by johnteske** [comment]
Still allow pinch-to-zoom, for closer investigation of score elements.

**Comment by johnteske** [comment]
vanilla JS solution

https://stackoverflow.com/a/39778831

`myButton.addEventListener('touchstart', preventZoom);`

**Comment by johnteske** [comment]
CSS solution:

```css
.score {
    -ms-touch-action: manipulation;
    touch-action: manipulation;
}
```
